#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PACKAGE_NAME="doorstop"
PACKAGE_PATH=$(python -c "import os; import $PACKAGE_NAME; print(os.path.dirname($PACKAGE_NAME.__file__))" 2>/dev/null)
MARKER_FILE="$PACKAGE_PATH/.doorstop_custom_patch_applied"


if [ -z "$PACKAGE_PATH" ]; then
	echo -e "$0 Error:\n\tdoorstop installation could not be found"
	exit 1
fi

if [ -f "$MARKER_FILE" ]; then
    echo "✅ Patch was previously applied. skip task..."
    exit 0
fi

patch -p1 -d "$PACKAGE_PATH" < "$SCRIPT_DIR/0001-Add-modifications-to-doorstop.patch"

if [ $? -eq 0 ]; then
    touch "$MARKER_FILE"
else
    echo "❌ Error: Applying doorstop patch has failed!"
    exit 1
fi