"""Executable links from central policies to concrete models, writers and resources.

References are strings to avoid importing adapters or feature modules into the
schema core. Architecture tests resolve them and check coverage, marker defaults,
explicit writer guards and all matching shipped resource versions. A model binding
means SchemaBoundModel checks serialization even for unchecked copies; a dict writer
binding means its function checks the actual envelope with require_current_payload.
This is an inventory, not dynamic dispatch or an assertion that arbitrary JSON is safe.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ModelBinding:
    family: str
    reference: str


@dataclass(frozen=True)
class MarkerBinding:
    """Central family ownership for class markers guarded at an outer boundary."""

    family: str
    reference: str


@dataclass(frozen=True)
class WriterBinding:
    family: str
    reference: str


@dataclass(frozen=True)
class ResourceBinding:
    family: str
    pattern: str
    discriminator: tuple[str, str] | None = None


SCHEMA_MODEL_BINDINGS: tuple[ModelBinding, ...] = (
    ModelBinding(
        "atlasdata-enrichments",
        "standards_atlas.adapters.atlasdata.knowledge_contract:AtlasDataKnowledge",
    ),
    ModelBinding(
        "atlasdata-knowledge-report",
        "standards_atlas.adapters.atlasdata.knowledge_contract:AtlasDataKnowledgeReport",
    ),
    ModelBinding(
        "cbox-enrichments",
        "standards_atlas.application.model.cbox:CBoxEnrichments",
    ),
    ModelBinding(
        "cbox-report",
        "standards_atlas.application.model.cbox:CBoxReport",
    ),
    ModelBinding(
        "clause-decision-plan",
        "standards_atlas.application.semantic_qualification.taxonomy_decisions:ClauseDecisionPlan",
    ),
    ModelBinding(
        "formal-ontology-resource",
        "standards_atlas.application.formal_semantics.ontology_definition:FormalOntologyDefinition",
    ),
    ModelBinding(
        "knowledge-adoption-batch",
        "standards_atlas.application.model.knowledge_adoption:KnowledgeAdoptionBatch",
    ),
    ModelBinding(
        "knowledge-adoption-report",
        "standards_atlas.application.model.knowledge_adoption:KnowledgeAdoptionReport",
    ),
    ModelBinding(
        "knowledge-evidence",
        "standards_atlas.adapters.atlasdata.knowledge_contract:EvidenceBlob",
    ),
    ModelBinding(
        "mixed-consensus",
        "standards_atlas.application.semantic_qualification.mixed_evidence:MixedConsensusReport",
    ),
    ModelBinding(
        "ontology-resource",
        "standards_atlas.application.semantic_ontology.definition:OntologyDefinition",
    ),
    ModelBinding(
        "partial-qualification-campaign",
        "standards_atlas.application.semantic_qualification.campaign_contract"
        ":QualificationCampaignArtifact",
    ),
    ModelBinding(
        "partial-qualification-manifest",
        "standards_atlas.application.semantic_qualification.qualification_cam"
        "paign_model:QualificationCampaign",
    ),
    ModelBinding(
        "partial-request-plan",
        "standards_atlas.application.semantic_qualification.partial_observati"
        "ons:PartialRequestPlan",
    ),
    ModelBinding(
        "partial-review-archive",
        "standards_atlas.application.semantic_qualification.review_package.ar"
        "chive:ReviewArchiveManifest",
    ),
    ModelBinding(
        "partial-review-candidates",
        "standards_atlas.application.semantic_qualification.review_package.pr"
        "eparation_model:CandidateIndex",
    ),
    ModelBinding(
        "partial-review-handoff",
        "standards_atlas.application.semantic_qualification.review_package.handoff:ReviewHandoff",
    ),
    ModelBinding(
        "partial-review-package",
        "standards_atlas.application.semantic_qualification.review_package.model:ReviewPackage",
    ),
    ModelBinding(
        "partial-review-profile",
        "standards_atlas.application.semantic_qualification.review_package.model:ReviewProfile",
    ),
    ModelBinding(
        "partial-review-publication",
        "standards_atlas.application.semantic_qualification.review_package.model:ReviewPublication",
    ),
    ModelBinding(
        "partial-review-selection-proposal",
        "standards_atlas.application.semantic_qualification.review_package.pr"
        "eparation_model:SelectionProposal",
    ),
    ModelBinding(
        "partial-review-state",
        "standards_atlas.application.semantic_qualification.review_package.model:ReviewState",
    ),
    ModelBinding(
        "partial-review-workbench-evidence",
        "standards_atlas.application.semantic_qualification.review_package.model:WorkbenchEvidence",
    ),
    ModelBinding(
        "partial-semantic-observation",
        "standards_atlas.application.semantic_qualification.partial_observati"
        "ons:PartialObservation",
    ),
    ModelBinding(
        "partial-semantic-reference",
        "standards_atlas.application.semantic_qualification.qualification_cam"
        "paign_model:SemanticReferenceSuite",
    ),
    ModelBinding(
        "qualification-consensus",
        "standards_atlas.application.semantic_qualification.consensus:ConsensusReport",
    ),
    ModelBinding(
        "qualification-matrix-manifest",
        "standards_atlas.application.semantic_qualification.qualification_mat"
        "rix:QualificationMatrixManifest",
    ),
    ModelBinding(
        "qualification-matrix-report",
        "standards_atlas.application.semantic_qualification.qualification_mat"
        "rix:QualificationMatrixReport",
    ),
    ModelBinding(
        "qualification-request-timing",
        "standards_atlas.application.semantic_qualification.performance:RequestTiming",
    ),
    ModelBinding(
        "review-workbench-state",
        "standards_atlas.application.semantic_qualification.review_package.model:WorkbenchState",
    ),
    ModelBinding(
        "semantic-profile-resource",
        "standards_atlas.application.semantic_classification.profile:SemanticProfile",
    ),
    ModelBinding(
        "semantic-task-resource",
        "standards_atlas.application.semantic_qualification.proposals:SemanticTaskDefinition",
    ),
    ModelBinding(
        "source-structure",
        "standards_atlas.application.model.source_structure:SourceStructure",
    ),
    ModelBinding(
        "standards-manifest",
        "standards_atlas.application.catalog.models:StandardCatalog",
    ),
    ModelBinding(
        "taxonomy-decision-rules",
        "standards_atlas.application.semantic_qualification.taxonomy_decisions:TaxonomyRuleProfile",
    ),
    ModelBinding(
        "public-semantic-annotation-manifest",
        "standards_atlas.adapters.atlasdata.semantic_annotation_writer:Public"
        "SemanticAnnotationManifest",
    ),
    ModelBinding(
        "complypack-workspace-manifest",
        "standards_atlas.adapters.complytime.complypack:ComplyPackWorkspaceManifest",
    ),
    ModelBinding(
        "complytime-evaluation-feedback-manifest",
        "standards_atlas.adapters.complytime.evaluation_feedback:EvaluationFeedbackManifest",
    ),
    ModelBinding(
        "governance-bundle-manifest",
        "standards_atlas.adapters.complytime.models:GovernanceBundleManifest",
    ),
    ModelBinding(
        "governance-bundle-traceability",
        "standards_atlas.adapters.complytime.models:GovernanceBundleTraceability",
    ),
    ModelBinding(
        "qualification-archive-receipt",
        "standards_atlas.adapters.evaluation.archive_receipt:QualificationArchiveReceipt",
    ),
    ModelBinding(
        "gemara-control-traceability",
        "standards_atlas.adapters.gemara.control_traceability:GemaraControlTraceabilityManifest",
    ),
    ModelBinding(
        "gemara-traceability",
        "standards_atlas.adapters.gemara.traceability:GemaraTraceabilityManifest",
    ),
    ModelBinding(
        "governance-policy-scaffold",
        "standards_atlas.adapters.governance.policy_scaffold:GovernancePolicyScaffoldManifest",
    ),
    ModelBinding(
        "alignment-result",
        "standards_atlas.application.model.alignment:AlignmentMetadata",
    ),
    ModelBinding(
        "alignment-overrides",
        "standards_atlas.application.model.alignment_review:AlignmentOverrideDocument",
    ),
    ModelBinding(
        "engineering-construction-contract",
        "standards_atlas.application.model.engineering_construction:Engineeri"
        "ngConstructionContract",
    ),
    ModelBinding(
        "formula-transcription",
        "standards_atlas.application.model.formula_transcription:FormulaTranscriptionArtifact",
    ),
    ModelBinding(
        "normalized-document",
        "standards_atlas.application.model.normalized_document:NormalizationMetadata",
    ),
    ModelBinding(
        "normalization-run",
        "standards_atlas.application.model.normalized_document:NormalizationRunMetadata",
    ),
    ModelBinding(
        "reference-candidate-document",
        "standards_atlas.application.model.reference_candidates:ReferenceDetectionMetadata",
    ),
    ModelBinding(
        "normalization-golden-case",
        "standards_atlas.application.qualification.golden_corpus:GoldenCaseManifest",
    ),
    ModelBinding(
        "partial-acceptance-profile",
        "standards_atlas.application.semantic_qualification.acceptance_profil"
        "es:PartialAcceptanceProfile",
    ),
    ModelBinding(
        "clause-evaluation-annotation",
        "standards_atlas.application.semantic_qualification.annotations:ClauseEvaluationAnnotation",
    ),
    ModelBinding(
        "evaluation-corpus",
        "standards_atlas.application.semantic_qualification.annotations:EvaluationCorpusManifest",
    ),
    ModelBinding(
        "applicability-detail-hitl-consensus",
        "standards_atlas.application.semantic_qualification.applicability_det"
        "ail_disagreement:ApplicabilityDetailHitlConsensusReport",
    ),
    ModelBinding(
        "applicability-detail-selection",
        "standards_atlas.application.semantic_qualification.applicability_det"
        "ail_enrichment:ApplicabilityDetailSelection",
    ),
    ModelBinding(
        "applicability-detail-enrichment-report",
        "standards_atlas.application.semantic_qualification.applicability_det"
        "ail_enrichment:ApplicabilityDetailEnrichmentReport",
    ),
    ModelBinding(
        "applicability-detail-failure-report",
        "standards_atlas.application.semantic_qualification.applicability_det"
        "ail_enrichment:ApplicabilityDetailFailureReport",
    ),
    ModelBinding(
        "applicability-policy-evaluation-report",
        "standards_atlas.application.semantic_qualification.applicability_pol"
        "icy_evaluation:ApplicabilityPolicyEvaluationReport",
    ),
    ModelBinding(
        "applicability-policy-run-state",
        "standards_atlas.application.semantic_qualification.applicability_pol"
        "icy_qualification:ApplicabilityPolicyRunState",
    ),
    ModelBinding(
        "applicability-policy-replay-report",
        "standards_atlas.application.semantic_qualification.applicability_pol"
        "icy_replay:ApplicabilityPolicyReplayReport",
    ),
    ModelBinding(
        "applicability-policy-run-report",
        "standards_atlas.application.semantic_qualification.applicability_pol"
        "icy_runner:ApplicabilityPolicyRunReport",
    ),
    ModelBinding(
        "annotation-qualification-report",
        "standards_atlas.application.semantic_qualification.qualification:Ann"
        "otationQualificationReport",
    ),
    ModelBinding(
        "qualification-coverage",
        "standards_atlas.application.semantic_qualification.qualification_cov"
        "erage:QualificationCoverage",
    ),
    ModelBinding(
        "annotation-review-form",
        "standards_atlas.application.semantic_qualification.review:ReviewForm",
    ),
    ModelBinding(
        "role-corpus-build-manifest",
        "standards_atlas.application.semantic_qualification.role_corpus:RoleCorpusBuildManifest",
    ),
    ModelBinding(
        "role-golden-corpus",
        "standards_atlas.application.semantic_qualification.role_corpus:RoleGoldenCorpus",
    ),
    ModelBinding(
        "qualification-run-selection",
        "standards_atlas.application.semantic_qualification.run_selection:Qua"
        "lificationRunSelection",
    ),
    ModelBinding(
        "benchmark-manifest",
        "standards_atlas.application.semantic_qualification.workflow:BenchmarkManifest",
    ),
    ModelBinding(
        "applicability-golden-corpus",
        "standards_atlas.application.semantic_qualification.applicability_cor"
        "pus:ApplicabilityGoldenCorpus",
    ),
    ModelBinding(
        "applicability-prediction-snapshot",
        "standards_atlas.application.semantic_qualification.applicability_har"
        "d_cases:ApplicabilityPredictionSnapshot",
    ),
)

SCHEMA_MARKER_BINDINGS: tuple[MarkerBinding, ...] = (
    MarkerBinding(
        "formal-semantic-projection",
        "standards_atlas.domain.model.formal_semantics:FormalSemanticProjection",
    ),
    MarkerBinding(
        "semantic-extraction",
        "standards_atlas.domain.model.semantic_extraction:DocumentSemanticExtraction",
    ),
    MarkerBinding(
        "structural-taxonomy-resource",
        "standards_atlas.application.structure.taxonomy_definition:StructuralTaxonomyDefinition",
    ),
    MarkerBinding(
        "governance-selection-profile",
        "standards_atlas.domain.model.governance_selection:GovernanceSelectionProfile",
    ),
    MarkerBinding(
        "governance-subject-group-profile",
        "standards_atlas.domain.model.governance_subject_groups:GovernanceSubjectGroupProfile",
    ),
    MarkerBinding(
        "normalization-qualification-run-report",
        "standards_atlas.application.qualification.report:QualificationRunReporter",
    ),
    MarkerBinding(
        "workflow-run-report",
        "standards_atlas.application.workflow.report:WorkflowRunReporter",
    ),
)


SCHEMA_WRITER_BINDINGS: tuple[WriterBinding, ...] = (
    WriterBinding(
        "normalization-qualification-run-report",
        "standards_atlas.application.qualification.report:QualificationRunReporter.write",
    ),
    WriterBinding(
        "workflow-run-report",
        "standards_atlas.application.workflow.report:WorkflowRunReporter.write",
    ),
    WriterBinding(
        "cascade-provenance",
        "standards_atlas.application.semantic_qualification.analysis_archive:"
        "write_cascade_provenance",
    ),
    WriterBinding(
        "cascade-replay",
        "standards_atlas.application.semantic_qualification.cascade_replay:replay_cascade",
    ),
    WriterBinding(
        "clause-decision-plan",
        "standards_atlas.application.semantic_qualification.taxonomy_diagnostics:"
        "diagnose_taxonomy_decisions",
    ),
    WriterBinding(
        "engineering-document",
        "standards_atlas.adapters.filesystem.document_repository:"
        "FileSystemEngineeringDocumentRepository.save",
    ),
    WriterBinding(
        "formal-semantic-projection",
        "standards_atlas.adapters.filesystem.formal_semantic_projection_repository:"
        "FileSystemFormalSemanticProjectionRepository.save",
    ),
    WriterBinding(
        "golden-corpus-proposal",
        "standards_atlas.application.semantic_qualification.consensus:_write_outputs",
    ),
    WriterBinding(
        "partial-cascade-audit",
        "standards_atlas.application.semantic_qualification.partial_cascade_audit:"
        "audit_partial_cascade",
    ),
    WriterBinding(
        "partial-cascade-report",
        "standards_atlas.application.semantic_qualification.partial_cascade:_write_report",
    ),
    WriterBinding(
        "partial-cascade-run",
        "standards_atlas.application.semantic_qualification.partial_cascade:run_partial_cascade",
    ),
    WriterBinding(
        "partial-proposal-run",
        "standards_atlas.application.semantic_qualification.partial_proposals:"
        "run_partial_proposals",
    ),
    WriterBinding(
        "partial-qualification-evaluation",
        "standards_atlas.application.semantic_qualification.campaign_evaluation:evaluate_campaign",
    ),
    WriterBinding(
        "partial-qualification-execution",
        "standards_atlas.application.semantic_qualification.campaign_execution:run_campaign",
    ),
    WriterBinding(
        "partial-qualification-repeat",
        "standards_atlas.application.semantic_qualification.campaign_execution:run_campaign",
    ),
    WriterBinding(
        "partial-qualified-activation",
        "standards_atlas.application.semantic_qualification.campaign_activation:activate_campaign",
    ),
    WriterBinding(
        "qualification-request-event",
        "standards_atlas.application.semantic_qualification.campaign_execution:"
        "FreshLedgerGateway.generate_structured",
    ),
    WriterBinding(
        "semantic-extraction",
        "standards_atlas.adapters.filesystem.semantic_extraction_repository:"
        "FileSystemSemanticExtractionRepository.save",
    ),
    WriterBinding(
        "semantic-extraction",
        "standards_atlas.cli.commands.evaluation_commands.qualification_archive:"
        "finalize_qualification_archive",
    ),
    WriterBinding(
        "semantic-readiness-checks",
        "standards_atlas.application.semantic_qualification.taxonomy_pilot:build_taxonomy_pilot",
    ),
    WriterBinding(
        "semantic-readiness-evaluation",
        "standards_atlas.application.semantic_qualification.semantic_readiness:"
        "evaluate_semantic_readiness",
    ),
    WriterBinding(
        "taxonomy-decision-report",
        "standards_atlas.application.semantic_qualification.taxonomy_diagnostics:"
        "diagnose_taxonomy_decisions",
    ),
    WriterBinding(
        "taxonomy-pilot-readiness",
        "standards_atlas.application.semantic_qualification.taxonomy_pilot:build_taxonomy_pilot",
    ),
    WriterBinding(
        "reviewed-alignment-integrity",
        "standards_atlas.adapters.alignment_review.repository:"
        "AlignmentReviewRepository.save_reviewed",
    ),
)


SCHEMA_RESOURCE_BINDINGS: tuple[ResourceBinding, ...] = (
    ResourceBinding(
        "semantic-task-resource",
        "src/standards_atlas/resources/semantic/tasks/**/task.yaml",
        None,
    ),
    ResourceBinding(
        "semantic-profile-resource",
        "src/standards_atlas/resources/semantic/profiles/**/profile.yaml",
        None,
    ),
    ResourceBinding(
        "ontology-resource",
        "src/standards_atlas/resources/ontologies/**/ontology.yaml",
        None,
    ),
    ResourceBinding(
        "formal-ontology-resource",
        "src/standards_atlas/resources/formal_ontologies/**/ontology.yaml",
        None,
    ),
    ResourceBinding(
        "structural-taxonomy-resource",
        "src/standards_atlas/resources/structure-taxonomies/**/taxonomy.yaml",
        None,
    ),
    ResourceBinding(
        "taxonomy-decision-rules",
        "src/standards_atlas/resources/semantic/taxonomy-decisions/**/rules.yaml",
        None,
    ),
    ResourceBinding(
        "taxonomy-decision-review",
        "src/standards_atlas/resources/semantic/taxonomy-decisions/**/review.yaml",
        None,
    ),
    ResourceBinding(
        "taxonomy-readiness-cases",
        "src/standards_atlas/resources/semantic/qualification/taxonomy-readiness-v1/cases.yaml",
        None,
    ),
    ResourceBinding(
        "standards-manifest",
        "manifests/*.yaml",
        ("manifest_type", "standards"),
    ),
    ResourceBinding(
        "qualification-matrix-manifest",
        "manifests/*.yaml",
        ("manifest_type", "qualification_matrix"),
    ),
    ResourceBinding(
        "partial-qualification-manifest",
        "cfg/evaluation/partial-cascade/qualification-campaign-v1.yaml",
        None,
    ),
    ResourceBinding(
        "partial-review-profile",
        "cfg/evaluation/partial-cascade/review-profile-v1.yaml",
        None,
    ),
)
