"""Domain model exports."""

from standards_atlas.domain.model.annotation import (
    AnnotationType,
    AnnotationVisibility,
    ClauseAnnotation,
)
from standards_atlas.domain.model.artifact_lineage import (
    ArtifactKind,
    ArtifactLineage,
    ArtifactReference,
    artifact_reference,
    canonical_content_hash,
)
from standards_atlas.domain.model.clause import Clause, ClauseType
from standards_atlas.domain.model.content import (
    CodeBlock,
    ContentBlock,
    FormulaBlock,
    ListBlock,
    ListItem,
    NoteBlock,
    PictureBlock,
    TableBlock,
    TableCell,
    TableRow,
    TextBlock,
    render_content_as_plain_text,
)
from standards_atlas.domain.model.document import DocumentType, EngineeringDocument
from standards_atlas.domain.model.doorstop_attributes import (
    DoorstopItemAttributes,
    DoorstopReference,
)
from standards_atlas.domain.model.identifiers import (
    AnnotationId,
    ClauseId,
    DocumentKey,
    StandardKey,
    StandardReference,
)
from standards_atlas.domain.model.knowledge_table import (
    IntegrityLevelRecommendation,
    KnowledgeCell,
    KnowledgeConcept,
    KnowledgeConceptKind,
    KnowledgeRecord,
    KnowledgeRecordId,
    KnowledgeRecordSource,
    KnowledgeRelation,
    KnowledgeRelationKind,
    KnowledgeTable,
    KnowledgeTableId,
    KnowledgeTableKind,
    RecommendationLevel,
    StructuredKnowledgeRecord,
    TechniqueRecommendation,
)
from standards_atlas.domain.model.reference_mention import (
    ReferenceMention,
    ReferenceMentionKind,
    ReferenceResolutionStatus,
    ReferenceTarget,
)
from standards_atlas.domain.model.relation import Relation, RelationType
from standards_atlas.domain.model.semantic_classification import (
    ApplicabilityFunction,
    DocumentStructure,
    DocumentStructureClassification,
    DomainFunctionClassification,
    KnowledgeKind,
    NormativeStatus,
    ProcessFunction,
    RelationScope,
    RoleRelation,
    RoleRelationClassCore,
    RoleRelationFamily,
    RoleRelationType,
    SemanticClassification,
    SemanticRelation,
    SemanticRelationKind,
    StatementFunction,
)
from standards_atlas.domain.model.source_evidence import (
    BoundingBox,
    CoordinateOrigin,
    SourceEvidence,
)
from standards_atlas.domain.model.standard import Standard
from standards_atlas.domain.model.structural_context import (
    StructuralAncestor,
    StructuralContext,
    StructuralNodeKind,
    StructuralReferenceEdge,
    StructuralScopeEdge,
    StructuralScopeMention,
    StructuralSiblingContext,
)
from standards_atlas.domain.model.structural_profile import (
    AnnexStatus,
    CanonicalDocumentSection,
    DomainCategory,
    SemanticSection,
    SemanticSectionRole,
    StructuralProfile,
)

__all__ = [
    "AnnexStatus",
    "CanonicalDocumentSection",
    "DomainCategory",
    "SemanticSection",
    "SemanticSectionRole",
    "StructuralProfile",
    "StructuralAncestor",
    "StructuralContext",
    "StructuralNodeKind",
    "StructuralReferenceEdge",
    "StructuralScopeEdge",
    "StructuralScopeMention",
    "StructuralSiblingContext",
    "ArtifactKind",
    "ArtifactLineage",
    "ArtifactReference",
    "AnnotationId",
    "AnnotationType",
    "AnnotationVisibility",
    "Clause",
    "ClauseAnnotation",
    "ClauseId",
    "ClauseType",
    "CodeBlock",
    "ContentBlock",
    "CoordinateOrigin",
    "DocumentKey",
    "BoundingBox",
    "DocumentType",
    "DoorstopItemAttributes",
    "DoorstopReference",
    "EngineeringDocument",
    "FormulaBlock",
    "ListBlock",
    "ListItem",
    "NoteBlock",
    "PictureBlock",
    "Relation",
    "RelationType",
    "ApplicabilityFunction",
    "DocumentStructure",
    "DocumentStructureClassification",
    "DomainFunctionClassification",
    "KnowledgeKind",
    "IntegrityLevelRecommendation",
    "KnowledgeTableId",
    "KnowledgeTableKind",
    "KnowledgeConcept",
    "KnowledgeConceptKind",
    "KnowledgeRelation",
    "KnowledgeRelationKind",
    "StructuredKnowledgeRecord",
    "RecommendationLevel",
    "TechniqueRecommendation",
    "KnowledgeTable",
    "KnowledgeRecordSource",
    "KnowledgeRecordId",
    "KnowledgeRecord",
    "KnowledgeCell",
    "NormativeStatus",
    "ProcessFunction",
    "RelationScope",
    "ReferenceMention",
    "ReferenceMentionKind",
    "ReferenceResolutionStatus",
    "ReferenceTarget",
    "RoleRelation",
    "RoleRelationClassCore",
    "RoleRelationFamily",
    "RoleRelationType",
    "SemanticClassification",
    "SemanticRelation",
    "SemanticRelationKind",
    "StatementFunction",
    "Standard",
    "StandardKey",
    "StandardReference",
    "SourceEvidence",
    "TableBlock",
    "TableCell",
    "TableRow",
    "TextBlock",
    "artifact_reference",
    "canonical_content_hash",
    "render_content_as_plain_text",
]
